AllCops:
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Vagrantfile'
  Exclude:
    - 'db/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'provision/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  RunRailsCops: true
  DisplayCopNames: true

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

PredicateName:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  Enabled: false

CharacterLiteral:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MultilineOperationIndentation:
  EnforcedStyle: indented

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '{}'
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
